extends Node

signal on_player_died
signal on_first_clicked
signal on_pause_menu_activated
signal on_energy_emptied
signal on_ending_reached
signal on_charging_zone_entered
signal on_charging_zone_exited
signal on_pietion_waited
signal on_gravity_zone_entered
signal on_gravity_zone_exited
